timeout: "240s"
serviceAccount: 552977366864-compute@developer.gserviceaccount.com
logsBucket: gs://clgcporg6-p001_cloudbuild
steps:
  - name: "us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/sample-app:latest"
    args: ["echo", "Testing Cloud Build Trigger with prebuilt image"]
